apiVersion: batch/v1
kind: Job
metadata:
  name: train-mnist-data
spec:
  template:
    metadata:
      name: train-mnist-data
    spec:
      containers:
      - name: train-mnist-data
        image: tensorflow/tf_grpc_test_server
        imagePullPolicy: IfNotPresent
        command: 
          - python
          - /var/tf-k8s/python/mnist_replica.py
        args:
          - --job_name=worker
          - --task_index=0
          - --num_gpus=0
          - --train_steps=500
          - --sync_replicas=False
          - --existing_servers=True
          - --ps_hosts=tf-ps-0.default.svc.cluster.local:2222
          - --worker_hosts=tf-worker-0.default.svc.cluster.local:2222,tf-worker-1.default.svc.cluster.local:2222
        volumeMounts:
        - name: tf-data
          mountPath: /tmp
      volumes:
      - name: tf-data
        persistentVolumeClaim:
          claimName: tf-data
      restartPolicy: Never
          