apiVersion: v1
kind: Pod
metadata:
  name: debug2
  namespace: default
spec:
  hostname: debug2
  subdomain: default
  containers:
  - image: debian:jessie
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
    name: debug2