apiVersion: v1
kind: Service
metadata:
  name: tf-worker
  labels:
    tf: worker
spec:
  type: ClusterIP
  ports:
  - port: 2222
  # *.tf-worker.default.svc.cluster.local
  selector:
    tf: worker
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: tf-worker
spec:
  serviceName: tf-worker
  replicas: 2
  template:
    metadata:
      labels:
        tf: worker
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: tf-worker
        image: tensorflow/tf_grpc_test_server
        args:
          - --cluster_spec=worker|tf-worker-0:2222;tf-worker-1:2222,ps|tf-ps-0:2222
          - --job_name=worker
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: shared
          mountPath: /shared
        - name: tf-data
          mountPath: /data
      volumes:
      - name: shared
        hostPath:
          path: /shared
      - name: tf-data
        persistentVolumeClaim:
          claimName: tf-data
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps
  labels:
    tf: ps
spec:
  type: ClusterIP
  ports:
  - port: 2222
  # *.tf-ps.default.svc.cluster.local
  selector:
    tf: ps
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: tf-ps
spec:
  serviceName: tf-ps
  replicas: 1
  template:
    metadata:
      labels:
        tf: ps
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: tf-ps
        image: tensorflow/tf_grpc_test_server
        args:
          - --cluster_spec=worker|tf-worker-0:2222;tf-worker-1:2222,ps|tf-ps-0:2222
          - --job_name=ps
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: shared
          mountPath: /shared
      volumes:
      - name: shared
        hostPath:
          path: /shared
