kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    type: local
    tf: worker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tf-data
  labels:
    tf: worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi