apiVersion: v1
kind: Pod
metadata:
  name: hello-world-1
spec:
  restartPolicy: Never
  containers:
  - name: hello
    image: busybox
    command: ["/bin/sh","-c"]
    args: ["export INDEX=${HOSTNAME##*-}"]