# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: tf-worker
  labels:
    tf: worker
spec:
  ports:
  - port: 2222
    targetPort: 2222
  clusterIP: None
  selector:
    tf: worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: tf-worker
spec:
  serviceName: "tf-worker"
  replicas: 1
  template:
    metadata:
      labels:
        app: tf
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "tf-bootstrap",
                "image": "tf-bootstrap",
                "args": [
                  "--data-dir=/data",
                  "--data-urls=" 
                  "--work-dir=/work-dir"
                ],
                "volumeMounts": [
                    {
                        "name": "tf-shared",
                        "mountPath": "/data"
                    },
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            },
            {
                "name": "peer-finder",
                "image": "alpine:3.4",
                "command": ["/work-dir/peer-finder"],
                "args": ["-on-start=\"/work-dir/on-start.sh\"", "-service=tf-worker"],
                "env": [
                  {
                      "name": "POD_NAMESPACE",
                      "valueFrom": {
                          "fieldRef": {
                              "apiVersion": "v1",
                              "fieldPath": "metadata.namespace"
                          }
                      }
                   }
                ],
                "volumeMounts": [
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            }
        ]'
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: tf-worker
        image: tf_grpc_server_minikube
        args: ["--job_name=worker"]
        ports:
        - containerPort: 2222
          name: tf-worker
        volumeMounts:
        - name: tf-shared
          mountPath: /data
        volumes:
        - name: workdir
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: tf-shared
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi